### ISSUE TITLE
Because `g_variant_builder_init_static`, mate-panel 1.28.6 fails to build with glib < 2.84.

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/mate-panel#1511]
As seen in [https://docs.gtk.org/glib/method.VariantBuilder.init_static.html](https://docs.gtk.org/glib/method.VariantBuilder.init_static.html), `g_variant_builder_init_static` is available in glib >= 2.84, which makes to fail build with glib < 2.84. I think this is a too much big change for a bugfix release. This basically set the minimum dependency for MATE Desktop to glib 2.84 (available in bleeding-edge distributions).

```
libtool: link: gcc -Wall -Wmissing-prototypes -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wl,-z -Wl,relro -o .libs/notification-area-applet notification_area_applet-main.o notification_area_applet-na-resources.o  ../../libmate-panel-applet/.libs/libmate-panel-applet-4.so ./.libs/libtray.a -lm -lX11 -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `_sn_watcher_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1933: undefined reference to `g_variant_builder_init_static'
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1934: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `sn_watcher_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1766: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-host-v0-gen.o): In function `sn_host_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-host-v0-gen.c:810: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o): In function `_sn_item_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4228: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o):/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4229: more undefined references to `g_variant_builder_init_static' follow
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:757: testtray] Error 1
make[5]: *** Waiting for unfinished jobs....
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `_sn_watcher_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1933: undefined reference to `g_variant_builder_init_static'
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1934: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `sn_watcher_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1766: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-host-v0-gen.o): In function `sn_host_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-host-v0-gen.c:810: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o): In function `_sn_item_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4228: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o):/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4229: more undefined references to `g_variant_builder_init_static' follow
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:753: notification-area-applet] Error 1
make[5]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[4]: *** [Makefile:898: all-recursive] Error 1
make[4]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[3]: *** [Makefile:619: all] Error 2
make[3]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[2]: *** [Makefile:452: all-recursive] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets'
make[1]: *** [Makefile:545: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6'
make: *** [Makefile:477: all] Error 2
```

**Comment by lukefromdc** [comment]
What commit brought this in? It may have to be reverted in 1.28 and kept only for 1.29-or redone for both while
avoiding g_variant_builder_init_static entirely

**Comment by lukefromdc** [comment]
Checking files from my last build of mate-panel (1.29/git master builds), I found file files containing
`g_variant_builder_init_static`
all of them behind this type of selector:
```
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_84
  g_variant_builder_init_static (&builder, G_VARIANT_TYPE ("a{sv}"));
#else
  g_variant_builder_init(&builder, G_VARIANT_TYPE ("a{sv}"));
#endif
```

**Comment by darkshram** [comment]
I have found the problem. Seems [https://github.com/mate-desktop/mate-panel/releases/download/v1.28.6/mate-panel-1.28.6.tar.xz](https://github.com/mate-desktop/mate-panel/releases/download/v1.28.6/mate-panel-1.28.6.tar.xz) was created using master branch instead of 1.28 branch. The **github** tarball for 1.28.6 does not contain any line with `g_variant_builder_init_static`.

**Comment by lukefromdc** [comment]
This means a re-release and version increment will in fact be needed

**Comment by vkareh** [comment]
This ticket is very confusing - mate-panel has no reference, at all, of `g_variant_builder_init_static`, either in `master` or `1.28`:
```
~/d/m/mate-panel (⎇ master) $ git grep g_variant_builder_init_static
~/d/m/mate-panel (⎇ master) $ 
```
```
~/d/m/mate-panel (⎇ 1.28) $ git grep g_variant_builder_init_static
~/d/m/mate-panel (⎇ 1.28) $ 
```
The only references are in automatically generated files in the notification area applet, which are system-dependent as far as I know. I built the tarbar using a fresh clone of the repo in the 1.28 branch, same HEAD I used for tagging 1.28.6.

**Comment by vkareh** [comment]
sure, but if you run instead
```
grep -rb1 g_variant_builder_init_static mate-panel-1.28.6
```
you will notice that every single one of those instances is wrapped by
```
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_84
```

**Comment by darkshram** [comment]
> sure, but if you run instead
> 
> ```
> grep -rb1 g_variant_builder_init_static mate-panel-1.28.6
> ```
> 
> you will notice that every single one of those instances is wrapped by
> 
> ```
> #if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_84
> ```

Try to build with glib 2.76. You will get:

```
libtool: link: gcc -Wall -Wmissing-prototypes -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wl,-z -Wl,relro -o .libs/notification-area-applet notification_area_applet-main.o notification_area_applet-na-resources.o  ../../libmate-panel-applet/.libs/libmate-panel-applet-4.so ./.libs/libtray.a -lm -lX11 -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `_sn_watcher_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1933: undefined reference to `g_variant_builder_init_static'
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1934: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `sn_watcher_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1766: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-host-v0-gen.o): In function `sn_host_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-host-v0-gen.c:810: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o): In function `_sn_item_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4228: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o):/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4229: more undefined references to `g_variant_builder_init_static' follow
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:757: testtray] Error 1
make[5]: *** Waiting for unfinished jobs....
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `_sn_watcher_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1933: undefined reference to `g_variant_builder_init_static'
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1934: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-watcher-v0-gen.o): In function `sn_watcher_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-watcher-v0-gen.c:1766: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-host-v0-gen.o): In function `sn_host_v0_gen_skeleton_dbus_interface_get_properties':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-host-v0-gen.c:810: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o): In function `_sn_item_v0_gen_emit_changed':
/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4228: undefined reference to `g_variant_builder_init_static'
./.libs/libtray.a(sn-item-v0-gen.o):/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area/status-notifier/sn-item-v0-gen.c:4229: more undefined references to `g_variant_builder_init_static' follow
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:753: notification-area-applet] Error 1
make[5]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[4]: *** [Makefile:898: all-recursive] Error 1
make[4]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[3]: *** [Makefile:619: all] Error 2
make[3]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets/notification_area'
make[2]: *** [Makefile:452: all-recursive] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6/applets'
make[1]: *** [Makefile:545: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/mate-panel-1.28.6'
make: *** [Makefile:477: all] Error 2
```
